version: '3'
services:
  server_node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - server_mongo
    links:
      - server_mongo
    volumes: 
    - .:/home/app
    - /home/app/node_modules
  server_mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=javier
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
      # mysql -> /var/lib/mysql
      # postgres -> /var/lib/postgresql/data

volumes:
  mongo-data:

